#!/usr/bin/env python
import os
import sys
import platform

env = SConscript("godot-cpp/SConstruct")

is_cross_arch_build = env["arch"] != platform.machine().lower()

if is_cross_arch_build and sys.platform == "linux":
    print("Cross-architecture build detected. Using custom flags.")

    env.Append(CCFLAGS=["--target=aarch64-linux-gnu"])
    env.Append(LINKFLAGS=["--target=aarch64-linux-gnu", "-fuse-ld=lld"])

# For reference:
# - CCFLAGS are compilation flags shared between C and C++
# - CFLAGS are for C-specific compilation flags
# - CXXFLAGS are for C++-specific compilation flags
# - CPPFLAGS are for pre-processor flags
# - CPPDEFINES are for pre-processor defines
# - LINKFLAGS are for linking flags

# tweak this if you want to use different folders, or more folders, to store your source code in.
env.Append(CPPPATH=["src/"])
sources = Glob("src/*.cpp")

if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../bin/openchamp.{}.{}.framework/openchamp.{}.{}".format(
            env["platform"], env["target"], env["platform"], env["target"]
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "../bin/openchamp{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
        source=sources,
    )

Default(library)
