on:
  workflow_call:

jobs:
  extension_compile_linux_amd64:
    name: "Compile Extension for Linux amd64"
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: |
            extensions/godot-cpp
            extensions/.sconsign.dblite
          save-always: true
          key: extension_cache_linux_amd64_4_2_2_stable

      - name: get submodules if cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: git submodule update --init --recursive

      - name: Install build dependencies
        run: sudo apt-get install -y scons

      - name: Compile the extension
        run: |
          cd extensions
          scons platform=linux target=template_debug compiledb=true use_llvm=true arch=amd64
          scons platform=linux target=template_release compiledb=true use_llvm=true arch=amd64
          cd ..

      - name: Upload extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension_linux_amd64
          path: bin

  export_game_linux_amd64:
    name: "Export for Linux amd64"
    runs-on: "ubuntu-24.04"
    needs: [ extension_compile_linux_amd64 ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: cache
        with:
          path: godot
          enableCrossOsArchive: true
          fail-on-cache-miss: true
          key: godot_4_2_2_stable_rev2

      - name: Retreive extension artifacts
        uses: actions/download-artifact@v4
        with:
          name: extension_linux_amd64
          path: bin

      - name: Create templates symlink
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          ln -s $(pwd)/godot/export_templates/4.2.2.stable ~/.local/share/godot/export_templates/4.2.2.stable

      - name: Create the build directory
        run: mkdir build

      - name: Export Client For Linux amd64
        run: ./godot/godot_linux --headless --export-release 'Client Linux/X11 amd64' project.godot

      - name: Export Server For Linux amd64
        run: ./godot/godot_linux --headless --export-release 'Server Linux/X11 amd64' project.godot

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux_builds_amd64
          path: build
